export default {
    ForYou: "For You",
    Fashion: "Fashion",
    Appliances: "Appliances",
    Mobiles: "Mobiles",
    Electronics: "Electronics",
    Home: "Home",
    Furniture: "Furniture",
    PersonalCare: "Personal Care",
    Toy_Baby: "Toy & Baby",
    Food_More: "Food & More",
    Sports_Hub: "Sports Hub",
    Travel: "Travel",
    Gift_Cards: "Gift Cards",
    Medicines: "Medicines",
    Home_Services: "Home Services",
    Bikes_Scooters: "Bikes % Scooters",
    Insurance: "Insurance",
    TopOffer: "Top Offers",
    Sale: "Sale is LIve",
    Delivery: "One Day delivery",
    MakeUp: "Makeup",
    Bluetooth : "Bluetooth Headphones",
    Toy_Games: "Toy & Games",
    Kurta: "Kurta & Sets",
    Dslr: "DSLR",
    BeanBags: "Bean Bags",
    Fashion1: "SpoylFashion",
    Fashion2: "SpoylFashion",
}

// module,exports = {STRINGS}